### ISSUE TITLE
DSHashes Link is no longer valid

### ISSUE THREAD

**Issue by ghost** [cheetz/thp2#2]
the wget command fails with a 404 error.
`root@kali:/opt# wget http://ptscripts.googlecode.com/svn/trunk/dshashes.py -O /opt/NTDSXtract/dshashes.py
--2016-12-20 12:45:31--  http://ptscripts.googlecode.com/svn/trunk/dshashes.py
Resolving ptscripts.googlecode.com (ptscripts.googlecode.com)... 173.194.206.82, 2607:f8b0:400d:c08::52
Connecting to ptscripts.googlecode.com (ptscripts.googlecode.com)|173.194.206.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-20 12:45:31 ERROR 404: Not Found.
`

**Comment by 0xdade** [comment]
I haven't found the new direct link, but you can get dshashes now by grabbing the whole repo. I think it got moved to archive status and that link broke.

Whole repo is here:
https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/ptscripts/source-archive.zip

File is:
ptscripts/trunk/dshashes.py

**Comment by ghost** [comment]
Found a direct link here: https://raw.githubusercontent.com/lanmaster53/ptscripts/master/dshashes.py

**Comment by cblanto7** [comment]
adding to what shredd and 0xdade have both said already:

thp2/setup.txt, line 139:
replace
> DSHashes:
> ●	Extracts user hashes in a user-friendly format for NTDSXtract
> ● wget http://ptscripts.googlecode.com/svn/trunk/dshashes.py -O /opt/NTDSXtract/dshashes.py
> 

with 

> ● wget https://raw.githubusercontent.com/lanmaster53/ptscripts/master/dshashes.py -O /opt/NTDSXtract/dshashes.py

**Comment by obitori** [comment]
There is a github copy of dshashes now, but it is slightly different than the one at githubusercontent.com listed above.  

https://github.com/bsi-group/dumpntds.git

The site says that the changes were made to reflect changes in the underlying ntds library.
